services:
  proof-server:
    image: "midnightnetwork/proof-server:4.0.0"
    command: ["midnight-proof-server --network testnet"]
    restart: on-failure
    ports:
      - "6300:6300"
    environment:
      RUST_BACKTRACE: "full"
