{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cocoa-monster.fullname" . }}
  labels:
    {{- include "cocoa-monster.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "cocoa-monster.fullname" . }}
            port:
              number: {{ .Values.service.port }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ include "cocoa-monster.fullname" . }}-tls
{{- end }}
