{{- if and (gt (int .Values.replicaCount) 1) .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cocoa-monster.fullname" . }}
  labels:
    {{- include "cocoa-monster.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "cocoa-monster.selectorLabels" . | nindent 6 }}
{{- end }}
