{{- if .Values.proofServer.enabled }}
{{- $name := printf "%s-proof-server" (include "cocoa-monster.name" .) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cocoa-monster.fullname" . }}-proof-server
  labels:
    {{- include "cocoa-monster.commonLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
spec:
  type: {{ .Values.proofServer.service.type }}
  ports:
    - name: proof
      port: {{ .Values.proofServer.service.port }}
      targetPort: proof
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
