#!/usr/bin/env bash

set -e

if [[ $(which ytt) == "" ]]; then
  echo "You will need to install ytt to repipe. https://carvel.dev/ytt/"
  exit 1
fi

target="${FLY_TARGET:-sandipndev}"
team=main
pipeline=cocoa-monster

TMPDIR=""
TMPDIR=$(mktemp -d -t repipe.XXXXXX)
trap "rm -rf ${TMPDIR}" INT TERM QUIT EXIT

ytt -f ci > ${TMPDIR}/pipeline.yml

echo "Updating pipeline @ ${target} (team=${team} pipeline=${pipeline})"

fly -t ${target} set-pipeline --team=${team} -p ${pipeline} -c ${TMPDIR}/pipeline.yml -n
fly -t ${target} unpause-pipeline --team=${team} -p ${pipeline}
