import { CompiledContract } from "@midnight-ntwrk/compact-js";
import {
  CompactTypeBytes,
  CompactTypeVector,
  persistentHash,
} from "@midnight-ntwrk/compact-runtime";
import {
  type ContractProviders,
  type DeployedContract,
  type FoundContract,
  deployContract,
  findDeployedContract,
} from "@midnight-ntwrk/midnight-js-contracts";
import { encodeUserAddress, type UserAddress } from "@midnight-ntwrk/ledger-v8";
import { pipe } from "effect";
import { type Observable } from "rxjs";
import { map } from "rxjs/operators";

import {
  Contract,
  ledger as readLedger,
  Side,
  type Witnesses,
} from "./managed/cocoa/contract/index.js";
import { decodeCocoaState, type CocoaState } from "./quote.js";
import {
  type CocoaPosition,
  type CocoaPrivateState,
  createCocoaPrivateState,
  witnesses,
} from "./witnesses.js";

export type CocoaContract = Contract<CocoaPrivateState, Witnesses<CocoaPrivateState>>;
export type CocoaCircuitId = "buy" | "close" | "resolve" | "redeem";
export type CocoaProviders = ContractProviders<CocoaContract, CocoaCircuitId, CocoaPrivateState>;
export type CocoaDeployed = DeployedContract<CocoaContract>;
export type CocoaFound = FoundContract<CocoaContract>;

export const COCOA_PRIVATE_STATE_ID = "cocoa" as const;

const ZERO_32 = new Uint8Array(32);

const oracleDescriptor = new CompactTypeVector(2, new CompactTypeBytes(32));

const padStringTo32 = (s: string): Uint8Array => {
  const bytes = new TextEncoder().encode(s);
  if (bytes.length > 32) throw new Error(`prefix "${s}" exceeds 32 bytes`);
  const buf = new Uint8Array(32);
  buf.set(bytes, 0);
  return buf;
};

/** Compute the public commitment from an oracle secret. */
export const computeOraclePubKey = (oracleSecret: Uint8Array): Uint8Array =>
  persistentHash(oracleDescriptor, [
    padStringTo32("cocoa:oracle:"),
    oracleSecret,
  ]);

const randomBytes32 = (): Uint8Array => {
  const buf = new Uint8Array(32);
  // crypto.getRandomValues is universal across Node 18+ and the browser.
  (globalThis.crypto ?? require("node:crypto").webcrypto).getRandomValues(buf);
  return buf;
};

const nowSeconds = (): bigint => BigInt(Math.floor(Date.now() / 1000));

/**
 * Contract binding using compact-js's CompiledContract effect builder.
 * Wires our generated Contract class with the witness implementations.
 * The compiled assets path resolves to where the UI's vite config serves
 * the .prover/.verifier/.zkir files generated by `compact compile`.
 */
export const compiledCocoaContract = pipe(
  CompiledContract.make<CocoaContract, CocoaPrivateState>(
    "cocoa",
    Contract as never,
  ),
  CompiledContract.withWitnesses(witnesses as never),
);

export type DeployCocoaMarketOptions = {
  question: string;
  initialLiquidity: bigint;
  closeTime: bigint;
  /**
   * Optional local oracle secret. If omitted and `oraclePubKey` is not
   * supplied, a fresh oracle secret is generated and stored in the deployer's
   * private state.
   */
  oracleSecret?: Uint8Array;
  /**
   * Optional external oracle commitment. When supplied, the browser does not
   * know the oracle secret and cannot resolve the market directly.
   */
  oraclePubKey?: Uint8Array;
  secretKey?: Uint8Array;
  positionNonce?: Uint8Array;
};

export const deployCocoaMarket = async (
  providers: CocoaProviders,
  opts: DeployCocoaMarketOptions,
): Promise<CocoaApi> => {
  const oracleSecret = opts.oracleSecret ?? (opts.oraclePubKey ? ZERO_32 : randomBytes32());
  const oraclePubKey = opts.oraclePubKey ?? computeOraclePubKey(oracleSecret);
  if (opts.oraclePubKey && opts.oracleSecret) {
    const expected = computeOraclePubKey(opts.oracleSecret);
    if (
      expected.length !== opts.oraclePubKey.length ||
      expected.some((b, i) => b !== opts.oraclePubKey![i])
    ) {
      throw new Error("oraclePubKey does not match oracleSecret");
    }
  }
  const initialPrivateState = createCocoaPrivateState(
    opts.secretKey ?? randomBytes32(),
    opts.positionNonce ?? randomBytes32(),
    oracleSecret,
  );
  // eslint-disable-next-line no-console
  console.debug("[cocoa-contract] deployContract input", {
    compiledContract: compiledCocoaContract,
    privateStateId: COCOA_PRIVATE_STATE_ID,
    args: [opts.question, String(opts.initialLiquidity), String(opts.closeTime)],
  });
  const deployed = await deployContract<CocoaContract>(providers, {
    compiledContract: compiledCocoaContract as never,
    privateStateId: COCOA_PRIVATE_STATE_ID,
    initialPrivateState,
    args: [
      opts.question,
      opts.initialLiquidity,
      opts.closeTime,
      oraclePubKey,
    ],
  });
  // eslint-disable-next-line no-console
  console.debug("[cocoa-contract] deployContract returned", deployed);
  return new CocoaApi(providers, deployed);
};

export const joinCocoaMarket = async (
  providers: CocoaProviders,
  contractAddress: string,
  opts: {
    secretKey?: Uint8Array;
    positionNonce?: Uint8Array;
    oracleSecret?: Uint8Array;
  } = {},
): Promise<CocoaApi> => {
  // 4.x scopes private state per contract address. Set it before any
  // get/set on the privateStateProvider, otherwise the level provider
  // throws "Contract address not set."
  providers.privateStateProvider.setContractAddress(contractAddress as never);
  const existing = await providers.privateStateProvider.get(
    COCOA_PRIVATE_STATE_ID,
  );
  const initialPrivateState =
    existing ??
    createCocoaPrivateState(
      opts.secretKey ?? randomBytes32(),
      opts.positionNonce ?? randomBytes32(),
      opts.oracleSecret ?? ZERO_32,
    );
  const found = await findDeployedContract<CocoaContract>(providers, {
    compiledContract: compiledCocoaContract as never,
    contractAddress: contractAddress as never,
    privateStateId: COCOA_PRIVATE_STATE_ID,
    initialPrivateState,
  });
  return new CocoaApi(providers, found);
};

export class CocoaApi {
  readonly contractAddress: string;
  readonly state$: Observable<CocoaState>;

  constructor(
    readonly providers: CocoaProviders,
    readonly deployed: CocoaFound,
  ) {
    this.contractAddress = deployed.deployTxData.public.contractAddress;
    this.state$ = providers.publicDataProvider
      .contractStateObservable(this.contractAddress as never, { type: "latest" })
      .pipe(map((cs) => decodeCocoaState(readLedger(cs.data))));
  }

  async buy(
    side: Side,
    stakeIn: bigint,
    amountOut: bigint,
  ): Promise<CocoaPosition> {
    const nonce = randomBytes32();
    await this.rotateNonce(nonce);
    const result = await this.deployed.callTx.buy(
      side,
      amountOut,
      stakeIn,
      nowSeconds(),
    );
    const amount = (result as { private: { result: bigint } }).private.result;
    const position: CocoaPosition = { side, amount, nonce };
    await this.appendOwnedPosition(position);
    return position;
  }

  async close(nowTs: bigint = nowSeconds()): Promise<void> {
    await this.deployed.callTx.close(nowTs);
  }

  async resolve(side: Side, nowTs: bigint): Promise<void> {
    await this.deployed.callTx.resolve(side, nowTs);
  }

  async resolveWithOracleSecret(
    side: Side,
    nowTs: bigint,
    oracleSecret: Uint8Array,
  ): Promise<void> {
    if (oracleSecret.length !== 32) {
      throw new Error("oracle secret must be 32 bytes");
    }
    this.providers.privateStateProvider.setContractAddress(
      this.contractAddress as never,
    );
    const ps = await this.providers.privateStateProvider.get(
      COCOA_PRIVATE_STATE_ID,
    );
    await this.providers.privateStateProvider.set(COCOA_PRIVATE_STATE_ID, {
      ...(ps ??
        createCocoaPrivateState(randomBytes32(), randomBytes32(), oracleSecret)),
      oracleSecret,
    });
    await this.resolve(side, nowTs);
  }

  async redeem(position: CocoaPosition, recipient: UserAddress): Promise<bigint> {
    await this.rotateNonce(position.nonce);
    const result = await this.deployed.callTx.redeem(
      position.side,
      position.amount,
      { bytes: encodeUserAddress(recipient) },
    );
    await this.markPositionRedeemed(position);
    return (result as { private: { result: bigint } }).private.result;
  }

  async ownedPositions(): Promise<readonly CocoaPosition[]> {
    this.providers.privateStateProvider.setContractAddress(
      this.contractAddress as never,
    );
    const ps = await this.providers.privateStateProvider.get(
      COCOA_PRIVATE_STATE_ID,
    );
    return ps?.ownedPositions ?? [];
  }

  async isOracle(): Promise<boolean> {
    this.providers.privateStateProvider.setContractAddress(
      this.contractAddress as never,
    );
    const ps = await this.providers.privateStateProvider.get(
      COCOA_PRIVATE_STATE_ID,
    );
    if (!ps) return false;
    if (ps.oracleSecret.every((b) => b === 0)) return false;
    const expected = computeOraclePubKey(ps.oracleSecret);
    const onchain = readLedger(
      (await this.providers.publicDataProvider.queryContractState(
        this.contractAddress as never,
      ))!.data,
    ).oraclePubKey;
    if (expected.length !== onchain.length) return false;
    for (let i = 0; i < expected.length; i++) {
      if (expected[i] !== onchain[i]) return false;
    }
    return true;
  }

  private async rotateNonce(nonce: Uint8Array): Promise<void> {
    this.providers.privateStateProvider.setContractAddress(
      this.contractAddress as never,
    );
    const ps = await this.providers.privateStateProvider.get(
      COCOA_PRIVATE_STATE_ID,
    );
    if (!ps) return;
    await this.providers.privateStateProvider.set(COCOA_PRIVATE_STATE_ID, {
      ...ps,
      positionNonce: nonce,
    });
  }

  private async appendOwnedPosition(position: CocoaPosition): Promise<void> {
    const ps = await this.providers.privateStateProvider.get(
      COCOA_PRIVATE_STATE_ID,
    );
    if (!ps) return;
    await this.providers.privateStateProvider.set(COCOA_PRIVATE_STATE_ID, {
      ...ps,
      ownedPositions: [...ps.ownedPositions, position],
    });
  }

  private async markPositionRedeemed(position: CocoaPosition): Promise<void> {
    const ps = await this.providers.privateStateProvider.get(
      COCOA_PRIVATE_STATE_ID,
    );
    if (!ps) return;
    await this.providers.privateStateProvider.set(COCOA_PRIVATE_STATE_ID, {
      ...ps,
      ownedPositions: ps.ownedPositions.filter(
        (p) => p.nonce !== position.nonce,
      ),
    });
  }
}
